"""add expires_at to booking

Revision ID: 0cc17b8400ad
Revises: f9b7e2d511fc
Create Date: 2026-07-21 18:35:43.525538

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0cc17b8400ad'
down_revision: Union[str, Sequence[str], None] = 'f9b7e2d511fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('booking', sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('booking', 'expires_at')
    # ### end Alembic commands ###
