"""squashed initial schema

Revision ID: f0a67b55bfe7
Revises: 
Create Date: 2026-09-15 06:15:27.597172

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f0a67b55bfe7'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # btree_gist lets a GiST exclusion index compare a plain equality column
    # (hall_id) alongside the range overlap check — required by the
    # no_overlapping_showtimes constraint on showtime below.
    op.execute("CREATE EXTENSION IF NOT EXISTS btree_gist")

    op.create_table('app_user',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("role IN ('customer', 'theater_manager', 'admin')"),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('cinema',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('discount',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('value', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('valid_from', sa.DateTime(timezone=True), nullable=False),
    sa.Column('valid_to', sa.DateTime(timezone=True), nullable=False),
    sa.Column('max_uses', sa.Integer(), nullable=True),
    sa.Column('used_count', sa.Integer(), server_default='0', nullable=False),
    sa.CheckConstraint('valid_to > valid_from'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('movie',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('genre', sa.String(length=100), nullable=True),
    sa.Column('release_year', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('seat_type',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('booking',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('discount_id', sa.BigInteger(), nullable=True),
    sa.Column('status', sa.String(length=20), server_default='pending', nullable=False),
    sa.Column('total_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('pending', 'confirmed', 'cancelled', 'expired')"),
    sa.ForeignKeyConstraint(['discount_id'], ['discount.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['app_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_booking_user', 'booking', ['user_id'], unique=False)
    op.create_table('cinema_manager',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('cinema_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['cinema_id'], ['cinema.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['app_user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'cinema_id')
    )
    op.create_table('hall',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('cinema_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cinema_id'], ['cinema.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cinema_id', 'name')
    )
    op.create_table('payment',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('booking_id', sa.BigInteger(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('status', sa.String(length=20), server_default='pending', nullable=False),
    sa.Column('idempotency_key', sa.String(length=255), nullable=False),
    sa.Column('provider_ref', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('pending', 'processing', 'succeeded', 'failed', 'refunded')"),
    sa.ForeignKeyConstraint(['booking_id'], ['booking.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key')
    )
    op.create_index('idx_payment_booking', 'payment', ['booking_id'], unique=False)
    op.create_table('seat',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('hall_id', sa.BigInteger(), nullable=False),
    sa.Column('row_label', sa.String(length=5), nullable=False),
    sa.Column('seat_number', sa.Integer(), nullable=False),
    sa.Column('seat_type_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['hall_id'], ['hall.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['seat_type_id'], ['seat_type.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hall_id', 'row_label', 'seat_number')
    )
    op.create_table('showtime',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('movie_id', sa.BigInteger(), nullable=False),
    sa.Column('hall_id', sa.BigInteger(), nullable=False),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ends_at', sa.DateTime(timezone=True), nullable=False),
    postgresql.ExcludeConstraint((sa.column('hall_id'), '='), (sa.text('tstzrange(starts_at, ends_at)'), '&&'), using='gist', name='no_overlapping_showtimes'),
    sa.CheckConstraint('ends_at > starts_at'),
    sa.ForeignKeyConstraint(['hall_id'], ['hall.id'], ),
    sa.ForeignKeyConstraint(['movie_id'], ['movie.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_showtime_hall_start', 'showtime', ['hall_id', 'starts_at'], unique=False)
    op.create_table('showtime_seat',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('showtime_id', sa.BigInteger(), nullable=False),
    sa.Column('seat_id', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.String(length=20), server_default='available', nullable=False),
    sa.Column('price_snapshot', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.CheckConstraint("status IN ('available', 'booked')"),
    sa.ForeignKeyConstraint(['seat_id'], ['seat.id'], ),
    sa.ForeignKeyConstraint(['showtime_id'], ['showtime.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('showtime_id', 'seat_id')
    )
    op.create_index('idx_showtime_seat_showtime', 'showtime_seat', ['showtime_id'], unique=False)
    op.create_table('booking_seat',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('booking_id', sa.BigInteger(), nullable=False),
    sa.Column('showtime_seat_id', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.String(length=20), server_default='active', nullable=False),
    sa.CheckConstraint("status IN ('active', 'cancelled')"),
    sa.ForeignKeyConstraint(['booking_id'], ['booking.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['showtime_seat_id'], ['showtime_seat.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_booking_seat_booking', 'booking_seat', ['booking_id'], unique=False)
    op.create_index('uq_active_booking_seat', 'booking_seat', ['showtime_seat_id'], unique=True, postgresql_where=sa.text("status = 'active'"))
    op.create_table('ticket',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('booking_seat_id', sa.BigInteger(), nullable=False),
    sa.Column('qr_code', sa.String(length=255), nullable=False),
    sa.Column('issued_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['booking_seat_id'], ['booking_seat.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('booking_seat_id'),
    sa.UniqueConstraint('qr_code')
    )
    # ### end Alembic commands ###

    # Materialized view for occupancy rate reporting — alembic's autogenerate
    # can't detect materialized views (they're raw SQL, not reflected
    # SQLAlchemy metadata), so this has to stay a hand-written op.execute()
    # rather than something autogenerate would ever regenerate on its own.
    op.execute("""
        CREATE MATERIALIZED VIEW IF NOT EXISTS mv_occupancy_rate AS
        SELECT
            st.id AS showtime_id,
            m.title AS movie_title,
            st.starts_at,
            c.id AS cinema_id,
            c.name AS cinema_name,
            h.id AS hall_id,
            h.name AS hall_name,
            h.capacity AS total_seats,
            COUNT(ss.seat_id) FILTER (WHERE ss.status = 'booked') AS booked_seats,
            ROUND(
                COUNT(ss.seat_id) FILTER (WHERE ss.status = 'booked')::numeric /
                NULLIF(h.capacity, 0) * 100,
                1
            ) AS occupancy_percent
        FROM showtime st
        JOIN hall h ON h.id = st.hall_id
        JOIN cinema c ON c.id = h.cinema_id
        JOIN movie m ON m.id = st.movie_id
        LEFT JOIN showtime_seat ss ON ss.showtime_id = st.id
        GROUP BY st.id, m.title, st.starts_at, c.id, c.name, h.id, h.name, h.capacity
        WITH NO DATA
    """)

    op.execute("""
        CREATE UNIQUE INDEX IF NOT EXISTS idx_mv_occupancy_rate_showtime
        ON mv_occupancy_rate (showtime_id)
    """)

    op.execute("""
        CREATE INDEX IF NOT EXISTS idx_mv_occupancy_rate_cinema
        ON mv_occupancy_rate (cinema_id)
    """)


def downgrade() -> None:
    """Downgrade schema."""
    op.execute("DROP MATERIALIZED VIEW IF EXISTS mv_occupancy_rate")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ticket')
    op.drop_index('uq_active_booking_seat', table_name='booking_seat', postgresql_where=sa.text("status = 'active'"))
    op.drop_index('idx_booking_seat_booking', table_name='booking_seat')
    op.drop_table('booking_seat')
    op.drop_index('idx_showtime_seat_showtime', table_name='showtime_seat')
    op.drop_table('showtime_seat')
    op.drop_index('idx_showtime_hall_start', table_name='showtime')
    op.drop_table('showtime')
    op.drop_table('seat')
    op.drop_index('idx_payment_booking', table_name='payment')
    op.drop_table('payment')
    op.drop_table('hall')
    op.drop_table('cinema_manager')
    op.drop_index('idx_booking_user', table_name='booking')
    op.drop_table('booking')
    op.drop_table('seat_type')
    op.drop_table('movie')
    op.drop_table('discount')
    op.drop_table('cinema')
    op.drop_table('app_user')
    op.execute("DROP EXTENSION IF EXISTS btree_gist")
    # ### end Alembic commands ###